### PR TITLE
Fix Dancun changes

### PR DESCRIPTION
**Pull request by halo3mic**
* Add `ParentBeaconBlockRoot` param to `BuildBlockArgs`
 * Make optional `Extra` field effective

### CODE REVIEW

**Review by lthibault — APPROVED** [review]
Nice one. Thank you!

**Comment by lthibault** [comment]
@halo3mic Any chance you could tackle the merge conflicts?

**Comment by halo3mic** [comment]
> @halo3mic Any chance you could tackle the merge conflicts?

On it!

**Review by lthibault — APPROVED** [review]
LGTM.  Waiting for CI, then merging.

**Comment by lthibault** [comment]
You're a hero @halo3mic. Thank you, sir!

**Pull request merged**
